language: objective-c
osx_image: xcode9.3
branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
  directories:
    - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
    - Carthage
    - vendor/bundle
xcode_workspace: RxCocoaNetworking.xcworkspace

before_install:
  - bundle install --path vendor/bundle
  - brew uninstall carthage
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/45dd24d8dfa7a2fb69812c678ceb34be0c16e295/Formula/carthage.rb # 0.29.0

script:
  - script/build

matrix:
  include:
    - stage: prepare carthage cache
      script:
        - carthage bootstrap --no-use-binaries --cache-builds
    - stage: logic tests
      xcode_scheme: RxCocoaNetworking-macOS
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - xcode_scheme: RxCocoaNetworking-iOS
    - xcode_scheme: RxCocoaNetworking-tvOS
    - xcode_scheme: RxCocoaNetworking-watchOS
    - stage: Danger
      script: bundle exec danger
    - stage: package manager tests
      script:
      - bundle exec pod repo update
      - bundle exec pod lib lint --allow-warnings # while RxSwift doesn't fix a warning
      env:
        - JOB=PODSPEC
    - os: osx
      language: generic
      script:
        - swift build
        - swift test
      env:
        - JOB=SWIFTPM_DARWIN
    - script:
        - carthage build --cache-builds --no-skip-current --platform macOS
    - script:
        - carthage build --cache-builds --no-skip-current --platform iOS
    - script:
        - carthage build --cache-builds --no-skip-current --platform tvOS
    - script:
        - carthage build --cache-builds --no-skip-current --platform watchOS
    - stage: Deploy GitHub
      script: skip
      before_deploy:
        - carthage build --no-skip-current --cache-builds
        - carthage archive RxCocoaNetworking
      deploy:
        - provider: releases
          api_key:
            secure: 
          file:
            - RxCocoaNetworking.framework.zip
          skip_cleanup: true
          overwrite: true
          on:
            repo: gobetti/RxCocoaNetworking
            tags: true
    - stage: Deploy Cocoapods
      script: skip
      env:
        - JOB=PODSPEC
      deploy:
        - provider: script
          script: bundle exec pod trunk push --allow-warnings # while RxSwift doesn't fix a warning
          skip_cleanup: true
          on:
            tags: true
